<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW4grmxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW4grmxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW4grmxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW4grmxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW4grmxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'W4grmxx',
    'container.build_id' => '9d1ef6db',
    'container.build_time' => 1633590191,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW4grmxx');
