<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjO5O09\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjO5O09/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHjO5O09.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHjO5O09\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHjO5O09\App_KernelDevDebugContainer([
    'container.build_hash' => 'HjO5O09',
    'container.build_id' => 'abbea2ea',
    'container.build_time' => 1633593644,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjO5O09');
